# 多執行緒環境下的單元測試

## 多執行緒測試的困難點

當系統成長到一個程度，效能的重要性就會慢慢浮現

「多執行緒」(Multi-threaded) 的設計，正是解決效能問題的方法之一

舉例來說，在「教務處網站」上，同學可以申請獎學金

假設無論結果如何，都要發個 Email 通知申請者

Email 的寄發牽扯到蠻大比重的 I/O 操作，不是一件很快的事

如果一封一封發，那執行時間就太久了

於是我們想用 Multi-threaded 的方式，來解決這個問題

回頭看我們先前提到的單元測試三步驟：準備資料、執行、檢查結果

但如果執行階段我們丟給 Multi-threaded 去執行，沒等執行完成就檢查結果，肯定會出問題

以下作者說三個常用的方法

## 方法一：回傳 Future 的任務

有些方法是會回傳值的，這種會比較好測，可以拿個 Future 去接

舉個最簡單例子，如果發 Email 後會回傳 boolean，代表成功或失敗

這時呼叫者可以利用 Future 的接口，來查看任務的回傳值

這個呼叫者當然也可以是個 Unit Test 的測項，這時我們就可以在測項裡驗證結果

程式 4-1：

```java
public class SendResultEmailService {

    private final Mailer mailer;
    private final ExecutorService executorService = Executors.newFixedThreadPool(300);

    // ... 中略
    
    public List<Future<Boolean>> send(List<ScholarshipResult> results) {
        // 建立 future
        List<Future<Boolean>> futures = new ArrayList<>();
        // for 迴圈寄信
        for (ScholarshipResult result : results) {
            futures.add(executorService.submit(() -> mailer.send(result)));
        }
        return futures;
    }
}
```

程式 4-2：

```java
@Test
void when_send_returns_future() {

    // 準備假 Mailer
    Mailer mailer = Mockito.mock(Mailer.class);
    SendResultEmailService service = new SendResultEmailService(mailer);

    // 假 Mailer 會回傳兩個 true，一個 false
    when(mailer.send(any(ScholarshipResult.class)))
            .thenReturn(true, true, false);

    // 跑起來
    List<Future<Boolean>> futures = service.send(
            Arrays.asList(
                    new ScholarshipResult(),
                    new ScholarshipResult(),
                    new ScholarshipResult()
            ));

    // 檢查 Future 裡 true 與 false 的個數
    int goods = 0;
    int bads = 0;
    for (Future<Boolean> future : futures) {
        if (future.get()) {
            goods++;
        } else {
            bads++;
        }
    }
    assertEquals(2, goods);
    assertEquals(1, bads);

}
```

這裡利用了 Future 的 get 介面，強迫測試等所有任務都執行完，再來檢查結果

### 測試也要重構

上面的測試程式碼，雖然可以成功測試方法

但如果不看註解，要花一番工服才能理解

這種測試正確有餘，表現力卻不足，如果能重構一下會更好

程式 4-3：

```java
@Test
void when_send_returns_future_refactor_the_test() {

    assume_mailer_execution_result_would_be(true, true, false);

    when_send_with_results(3);

    then_counts_in_futures_will_be(true, 2);
    then_counts_in_futures_will_be(false, 1);
}
```

這裡用了一些手法，刻意將一些細節隱藏起來

讓測項的第一層只剩下一些「商務邏輯」的敘述

其實讀者看上面的程式碼就夠了，並不需要知道太細，這就是重構的目的

有些人可能不會去重構測試程式，但測試也是程式，也會有壞味道

「高效程序員的 45 個習慣：敏捷開發修煉之道」一書中提到

重構的最佳時機，就是測試通過的時候

這時腦中，對剛剛寫的東西印象還很深刻，重構效果最好

所以，測試通過了，就先考慮重構，程式和測試都要

## 方法二：間接驗測，分別驗任務行為與排程行為

那麼，總有任務是不回傳值的吧？又該怎麼測？

像前一篇有講到，如果設計程式時，把 Command 與 Query 分開

那就沒有辦法透過 Future 檢驗回傳值了

其實，還是可以**測行為**

一個多執行緒的功能，都會由兩個行為組成：

一個是「任務本身的行為」

一個是「將任務排程的行為」(以 Java 來說，就是 ExecuteService 的 submit 行為)

這時，我們可以將兩件事情分別測試

先視你的商務邏輯，單獨驗測任務本身的行為

再將任務做成假物件，單獨驗測「排程」的行為有沒有如預期發生

至於要怎麼「驗行為」，這個我們上篇聊過了

像這樣間接驗測，其實是建立於我們對依賴本身的信任

當任務的行為本身是檢驗過的、正確的，只要確保有依需求發送任務就好

## 方法三：利用 ArgumentCaptor 攔下來測

前面兩種方法，適用於工作上大部分情形

只要能把「任務本身的行為」與「將任務排程的行為」分開，就也沒那麼難

但有時候，任務本身是透過「匿名類別」來定義的

例如程式 4-4：

```java
public void silentSend(List<ScholarshipResult> results) {
    for (ScholarshipResult result : results) {
        executorService.submit(() -> mailer.silentSend(result));
    }
}
```

程式 4-4 用了Java 的 `ExecutorService`

對它不熟悉的話，就把它理解成一個可以幫忙發射 Thread 的工具就好

這裡被 submit 出去的 Runnable 是匿名的

內容就只是叫 mailer 去發信，該方法也沒有回傳值

這時，只好請出 Mockito 的 `ArgumentCaptor` 了

`ArgumentCaptor` 的功能是在測試中假扮成受測方法的參數

等結束後再回頭告訴你，剛剛在它身上發生了什麼事

用講的會有點抽象，直接來看實際的測試該怎麼寫

程式 4-5：

```java
class SendResultEmailServiceSilentTest {
    @Test
    void silent_send() {
        // 準備假資料
        Mailer mailer = Mockito.mock(Mailer.class);
        ExecutorService es = Mockito.mock(ExecutorService.class);
        SendResultEmailService service = new SendResultEmailService(mailer, es);

        // 跑起來
        service.silentSend(
                Arrays.asList(
                        new ScholarshipResult(),
                        new ScholarshipResult(),
                        new ScholarshipResult()
                )
        );

        // 使用 ArgumentCaptor 假扮真正的參數給 ExecutorService 用
        ArgumentCaptor<Runnable> captor = ArgumentCaptor.forClass(Runnable.class);
        Mockito.verify(es, Mockito.times(3)).submit(captor.capture());

        // 取出所有的 Runnable 並執行
        List<Runnable> runnables = captor.getAllValues();
        runnables.forEach(
                Runnable::run
        );

        // 驗證是否真的有呼叫 silentSend 三次
        Mockito.verify(mailer, Mockito.times(3)).silentSend(any(ScholarshipResult.class));
    }
}
```

## 好測，就會好用

多線程的程式要好測，還得「設計的結構」配合才行

例如「任務」與「排程」如果混在一起實現，測起來就會比較麻煩

「高效程序員的 45 個習慣」以及另一本「The Pragmatic Programmer」

都有提到一個好習慣：「讓測試當你程式的第一個使用者」

先自己測看看，才知道人家用你的功能，會不會好用

好測，就會好用

作者推薦書籍：《高效程序員的 45個習慣:敏捷開發修煉之道》

# 單元測試與例外處理

本節將進行討論例外處理 (try-catch)

同樣是 try-catch，處理得好不好，結果差很多

例外處理做得很差，雖然還是能把功能做出來，但是後續維護上就會很麻煩

現代軟體開發，花在維護與修改上的成本，比起開發本身，要高出許多

做出難以維護的功能，不是以後才會吃虧，是很快就會吃虧

## 例外處理簡介

在程式中，會遇到的例外有兩種情形：

1. 可修復

   例如網路突然斷了一下，或是檔案不存在

2. 不可修復

   例如應該要有值的地方竟然是 null，出 bug 了


可修復的例外稱為 Checked Exception，可以 retry、採取替代方案、或是 log 下來

不可修復的意外稱為 Unchecked Exception，代表程式有 bug，要讓 RD 排查解決

以下介紹兩種較常見的處理方式，以及對應的測試方法

## 攔下來處理

任何時刻底層出錯，你覺得在這一層「應該處理，也有能力處理」時

就可以將特定 Exception 攔下來，並在 catch 裡面做對應的處理

例如：在後端的 Controller 層收到了 Service 層拋出來的例外，應該要攔下來處理

因為如果不處理，這個 Request 就會整個出錯

以 Java 的 Spring Boot 來說

會使得前端網頁收到一個「500 - Internal Server Error」訊息

當看到這個畫面，用戶只知道「有地方出錯了」，但其他就一無所知（或是看不懂）

假設要回傳前端認識的錯誤代碼，那麼 Controller 層也有能力處理

自行組成前後端講好的資料格式並回傳

此回傳可能是代表錯在前端的 400，也可能還是代表錯在後端的 500

但無論如何，都應該還要在回傳數據裡，塞入足夠讓前端分辨的資訊

才不會搞得用戶一頭霧水，不知道哪裡出問題

舉例來說

假設要做一個「學生註冊」的網頁與 API

處理到一半發現，根本沒有這個學生的資料

這時應該要回傳，前後端都懂的一個資料格式

讓前端有足夠訊息，顯示正確畫面給用戶看

程式 4-6

```java
@PostMapping("/register")
public ResponseEntity<ApiResponse> createTeam(@RequestBody RegisterRequest request) {
    try {
        service.execute(request);
        // ApiResponse 是前後端共同講好的回傳資料格式
        // 這裡與前端說好，如果成功就直接回 200 就好，內容可以「空白」
        return ResponseEntity.ok(ApiResponse.empty());
    } catch (StudentNotExistException e) {
        // 我們不認為這是系統出錯，所以寫 info 就好，以免過多 error 在 log 裡干擾閱讀
        log.info("Student not found. " + e.getMessage());
        // 用 Http 400 告訴前端這是用戶有問題，
        // 並在 body 裡帶一個特殊代碼「987」，代表「用戶不存在」
        return ResponseEntity.status(400).body(ApiResponse.bad(987));
    }
}
```

接下來

就趕緊藉由測項來檢查程式，有沒有把這兩個邏輯分支都寫對

程式 4-7

```java
@SpringBootTest
@AutoConfigureMockMvc
class RegisterControllerTest {
    private final ObjectMapper objectMapper = new ObjectMapper();

    @Autowired
    private MockMvc mockMvc;
    @MockBean
    private RegisterService service;

    @Test
    void all_ok() throws Exception {
        // 使用 MockMvcRequestBuilders 測試 api
        MockHttpServletRequestBuilder postRequest = MockMvcRequestBuilders
                .post("/register")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(new RegisterRequest(35L)));
        // 測試，並檢查結果
        mockMvc.perform(postRequest)
                .andExpect(status().is(HttpStatus.OK.value()));
    }

    @Test
    void student_not_found() throws Exception {
        // 建立一個會拋錯的 RegisterService 假物件
        Mockito.doThrow(new StudentNotExistException("ANY_MESSAGE"))
                .when(service)
                .execute(any(RegisterRequest.class));
        // 測試 api 的物件
        MockHttpServletRequestBuilder postRequest = MockMvcRequestBuilders
                .post("/register")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(new RegisterRequest(35L)));
        // 測試，並檢查結果
        mockMvc.perform(postRequest)
                .andExpect(status().is(HttpStatus.BAD_REQUEST.value()))
                .andExpect(content().json(objectMapper.writeValueAsString(ApiResponse.bad(987))));
    }
}
```

## 攔下來轉拋

例外處理的另一種方式，就是「攔下來轉拋」

例如底層也許會拋個 IOException

而這一層並沒有能力處理，或是在架構上由上一層處理比較適合

這時就可以攔下來以後，在 catch 裡轉包一個跟上層講好的 Exception 出去

至於上層要怎麼處理，這層就不用管了

一樣是剛剛「學生註冊」的例子

假設在第二層的 Service，收到來自 Repository 層的 Exception

並且從各個方訊息判斷出這個情況應該是「學生不存在」

由於「學生不存在」這件事應該要回報給前端顯示，訊息的發送應該要讓 Controller 進行

事實上，也只有 Controller 應該要知道前端想收什麼 Error Code

因此，這時就適合「攔下來轉拋」這個做法

程式 4-8

```java
public void execute(RegisterRequest request) {
    try {
        repository.register(request);
    } catch (DataNotFoundException e) {
        throw new StudentNotExistException("Student not exists", e);
    }
}
```

這裡會轉拋一個例外，所以測試就不能讓他順利跑完

而是要讓在測項裡把例外抓下來，並檢查這個例外長得是否符合預期

程式 4-9

```java
class RegisterServiceTest {
    private final StudentRepository repository = Mockito.mock(StudentRepository.class);

    @Test
    void when_student_not_exists() {
        // 給定一個不存在，會拋錯的資料
        given_student_NOT_exists(35L);
        try {
            // 建立 service 並執行
            create_register_service().execute(request(35L));
            // 應該要拋出錯誤，但沒拋的話，就會執行 test fail
            fail("should throw exception");
        } catch (StudentNotExistException e) {
            // 檢查是否有拋出例外和訊息(訊息不用測太細)
            assertThat(e).hasMessageContaining("not exists");
        }
    }
    
    private void given_student_NOT_exists(long studentId) {
        Mockito.doThrow(new DataNotFoundException())
                .when(repository).register(request(studentId));
    }
    
    private RegisterService create_register_service() {
        return new RegisterService(repository);
    }

    private RegisterRequest request(long studentId) {
        return new RegisterRequest(studentId);
    }
}
```

## 測法不只一種

主流的測試框架，都有提供蠻多方法可以測例外的

例如程式 4-10

```java
@Test
void when_student_not_exists_alternative() throws DataNotFoundException {
    // 給定一個不存在，會拋錯的資料
    given_student_NOT_exists(35L);
    // 設定執行方法時，應該要拋出例外
    StudentNotExistException actualException = Assertions.assertThrows(
            StudentNotExistException.class,
            () -> create_register_service().execute(request(35L))
    );
    // 檢查是否有拋出例外和訊息(訊息不用測太細)
    assertThat(actualException).hasMessageContaining("not exists");
}
```

其實邏輯和上一小節一樣，只是語法不同

大家可以自行感受一下，喜歡哪一個版本

## 為什麼要轉拋？而不直接往外丟就好？

「迪米特法則」，又稱為最少知識原則（Least Knowledge Principle）

包含三大原則，其中一項就是「只與你直接認識的人交談」

**Repositry 一定要操作 DB 嗎**？

它能操作 API 吧？它能跟 Redis 拿吧？它可以操作本機上的檔案吧？

既然可以，那憑什麼 Service 非得認識 SQLException 不可？

說到底，Repository 應該要是 Service 定義好的介面，根據 OOP 的依賴反轉原則

Service 不應該直接依賴於 Repository 的實作，而應該「共同依賴一個介面」才對

既然實作可以多變，那收到 Exception 的那一個實作，就不應該直接轉拋出去

而是轉化成它與上層共同依賴的介面所定義好的 Exception

否則就是強迫呼叫方，去認識他原本不該認識的人，違反迪米特法則

## 為什麼不用 Runtime Exception?

作者結論：「很簡單，因為我不喜歡。」

不是 Runtime Exception 不好，只是作者不喜歡而已

有讀過 Clean Code 都知道，Uncle Bob 在書中建議大家盡量多用 Runtime Exception

但為什麼他會這麼建議？

Uncle Bob 認為，有很多人會把丟例外跟處理例外的邏輯，放在好幾層遠的地方

而語言與框架也允許我們這麼做

然而萬一底層有需要修改，沿途的所有類別都得修改簽名，違反了「開放封閉原則」

但作者覺得這種做法，使得最上層的人「跨層」跑去認識他不該認識的 Exception

例如處在系統邊界的 Controller

應該是要擔任框架與 Service 的橋樑、轉化物件與資料、讓兩邊能順利溝通

結果到頭來整天在處理一些表示 DB 連線異常、檔案不存在...等等錯誤

它應該要處理語意上，更高階的錯誤才是，例如「學生不存在」、「成績未達標」…等等

因為它是負責把這些語意，再轉成前端看得懂的訊息的人啊！

回到 Uncle Bob 描述的場景，使程式違反開放封閉原則的元兇

並不是 Checked Exception 本身，而是「不良的設計習慣」

收到底層丟出的例外後，不假思索的往外拋，才會造成違反開放封閉的問題

「全面改用 Runtime Exception」，雖能解決問題，但副作用卻是違反迪米特法則

因此作者認為這不是一個非常好的解法

然而，不可否認像這樣作者的解法，每層都要考慮到底是要轉包還是處理

真的很麻煩，要一直想事情、一直 try-catch 很討厭

所以針對「使用 Runtime Exception」這件事

作者只說了「自己不喜歡」，沒說各位不能用，更沒說 Uncle Bob 不對

沒有完美的解法，看自己想承擔「哪一種副作用」而已